version: "3"

services:
  app:
    build:
      dockerfile: ./DockerFile
      context: .
      target: ${NODE_ENV}
    ports:
      - '3000:3000'
    volumes:
      - ".:/usr/app"
    depends_on:
      - database
      - queue
    networks:
      rede:
  database:
    image: mongo:4.4.5
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - './data:/data/db'
    networks:
      rede:
  queue:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - '15672:15672'
      - '${RABBITMQL_PORT}:5672'
    networks:
      rede:
networks:
  rede:
    driver: bridge
