version: "3.4"

services:
  app:
    build:
      dockerfile: ./DockerFile
      context: .
      target: ${NODE_ENV}
    # command: bash -c 'yarn start:dev'
    command: sh -c "dockerize -wait tcp://queue:5672 -timeout 300s -wait-retry-interval 5s && yarn && yarn start:dev"
    ports:
      - ${PORT_SERVER}:${PORT_SERVER}
    volumes:
      - ".:/usr/app"
    depends_on:
      - database
      - queue
    restart: on-failure
    networks:
      rede:
  database:
    image: mongo:4.4.5
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - './data:/data/db'
    networks:
      rede:
  queue:
    image: rabbitmq:3-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - '15672:15672'
      - '${RABBITMQL_PORT}:5672'
    networks:
      rede:
networks:
  rede:
    driver: bridge
