version: "3"

services:
  app:
    build:
      dockerfile: ./DockerFile
      context: .
    ports:
      - '3000:3000'
    volumes:
      - ".:/usr/app"
    depends_on:
      - database
    networks:
      rede:
  database:
    image: mongo:4.4.5
    ports:
      - '${DB_PORT}:27017'
    volumes:
      - './data:/data/db'
    networks:
      rede:
networks:
  rede:
    driver: bridge
